export interface IUser {
    userId: number;
    userNumDoc: string;
    userName: string;
    userLastName: string;
    userAddress: string;
    userPhone: string;
    userEmail: string;
    userPassword: string;
    userState: boolean;
    userDocType: UserDocType;

}



export interface UserDocType {
    docTypeId: number;
    docTypeName: string;
}

// Generated by https://quicktype.io

// export interface userResponse {
//     code:    number;
//     message: string;
//     data:    IUser[];
//     success: boolean;
// }

// export interface IUser {
//     userId:       number;
//     userNumDoc:   string;
//     userName:     string;
//     userLastName: string;
//     userAddress:  string;
//     userPhone:    string;
//     userEmail:    string;
//     userPassword: string;
//     userState:    boolean;
//     userDocType:  UserDocType;
// }

// export interface UserDocType {
//     docTypeId:   number;
//     docTypeName: string;
// }
