
// Generated by https://quicktype.io

export interface ApiResponse {
    code:    number;
    message: string;
    data:    [];
    success: boolean;
}

export interface IUser {
    userId:       number;
    userNumDoc:   string;
    userName:     string;
    userLastName: string;
    userAddress:  string;
    userPhone:    string;
    userEmail:    string;
    userPassword: string;
    userState:    boolean;
    userDocType:  TypeDocs;
}

export interface TypeDocs {
    docTypeId:   number;
    docTypeName: string;
}
